 --- #YAML:1.0
 name: Acme-ICHC-Lolcats
 abstract: Retrieves the latest from ICanHasCheezburger.
 version: 0.01
 license: perl
 distribution_type: module
 requires:
   LWP::UserAgent: 0
 build_requires:
   Test: 0
 urls:
   license: http://dev.perl.org/licenses/
 meta-spec:
   version: 1.3
   url: http://module-build.sourceforge.net/META-spec-v1.3.html
 generated_by: Module::Build version 0.20